version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    dev-dependencies:
    android-dependencies:
      patterns:
        - "Xamarin.*"
        - "Xamarin.*"
    unittest-dependencies:
      patterns:
        - "xunit"
        - "xunit.*"
        - "XunitXml.*"
        - "Microsoft.NET.Test.Sdk"
    analyzers:
      patterns:
        - "AsyncFixer"
        - "*Analyzer*"
