pool:
  vmImage: windows-2019

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

steps:
- task: DotNetCoreCLI@2
  displayName: 'Install SignClient'
  inputs:
    command: custom
    custom: tool
    arguments: 'install --tool-path . SignClient'

- task: PowerShell@2
  displayName: 'Run Cake Build'
  inputs:
    targetType: filePath
    filePath: .\build.ps1
    arguments: "--verbosity=Verbose --signing_secret='$(SIGNING_SECRET)' --signing_user='$(SIGNING_USER)' --nuget_source='$(NUGET_SOURCE)' --nuget_apikey='$(NUGET_APIKEY)'"